/** Unit 1 Happy Holiday — 初二英语 · 简体中文释义 */
window.UNIT = {
  id: "unit1",
  title: "Unit 1",
  theme: "Happy Holiday",
  themeZh: "快乐假期",
  bigQuestion: "What makes a great holiday?",
  bigQuestionZh: "怎样才算一次很棒的假期？",
  goals: [
    { en: "Talk about holiday activities and experiences", zh: "谈论假期活动和经历" },
    { en: "Use indefinite pronouns", zh: "使用不定代词（someone / anything / nowhere 等）" },
    { en: "Express feelings about holidays", zh: "表达对假期的感受" },
    { en: "Explore the benefits of holiday experiences", zh: "思考假期经历带来的收获" },
  ],

  vocab: [
    { en: "ancient", ipa: "/ˈeɪnʃənt/", pos: "adj.", zh: "古代的；古老的", tip: "ancient buildings 古建筑" },
    { en: "camp", ipa: "/kæmp/", pos: "n./v.", zh: "度假营；营地；露营", tip: "summer camp 夏令营；go camping 去露营" },
    { en: "landscape", ipa: "/ˈlændskeɪp/", pos: "n.", zh: "风景；景色" },
    { en: "strange", ipa: "/streɪndʒ/", pos: "adj.", zh: "奇怪的；陌生的", tip: "相关词：stranger 陌生人" },
    { en: "vacation", ipa: "/vəˈkeɪʃn/", pos: "n.", zh: "假期；度假", tip: "take a vacation 去度假（美式）" },
    { en: "fantastic", ipa: "/fænˈtæstɪk/", pos: "adj.", zh: "极好的；吸引人的" },
    { en: "town", ipa: "/taʊn/", pos: "n.", zh: "镇；商业区", tip: "old town 古镇" },
    { en: "breath", ipa: "/breθ/", pos: "n.", zh: "呼吸的空气；一口气" },
    { en: "especially", ipa: "/ɪˈspeʃəli/", pos: "adv.", zh: "尤其；特别" },
    { en: "anywhere", ipa: "/ˈeniweə(r)/", pos: "adv./pron.", zh: "在任何地方；随便哪个地方" },
    { en: "nothing", ipa: "/ˈnʌθɪŋ/", pos: "pron.", zh: "没有事；没有任何东西" },
    { en: "guide", ipa: "/ɡaɪd/", pos: "n./v.", zh: "导游；指南；给某人领路", tip: "tour guide 导游" },
    { en: "scenery", ipa: "/ˈsiːnəri/", pos: "n.", zh: "风景；景色", tip: "enjoy the scenery 欣赏风景" },
    { en: "silk", ipa: "/sɪlk/", pos: "n.", zh: "丝绸；（蚕）丝" },
    { en: "scarf", ipa: "/skɑːf/", pos: "n.", zh: "围巾；披巾", tip: "silk scarf 丝巾" },
    { en: "ready", ipa: "/ˈredi/", pos: "adj.", zh: "准备好的；现成的", tip: "be ready to do sth 准备好做某事" },
    { en: "somewhere", ipa: "/ˈsʌmweə(r)/", pos: "adv./pron.", zh: "在某处；某个地方" },
    { en: "myself", ipa: "/maɪˈself/", pos: "pron.", zh: "我自己", tip: "by myself 独自" },
    { en: "hotel", ipa: "/həʊˈtel/", pos: "n.", zh: "旅馆；旅社" },
    { en: "comfortable", ipa: "/ˈkʌmftəbl/", pos: "adj.", zh: "使人舒服的；舒适的" },
    { en: "bored", ipa: "/bɔːd/", pos: "adj.", zh: "厌倦的；烦闷的", tip: "feel bored 感到无聊" },
    { en: "sky", ipa: "/skaɪ/", pos: "n.", zh: "天；天空" },
    { en: "towards", ipa: "/təˈwɔːdz/", pos: "prep.", zh: "向；朝", tip: "也可写作 toward" },
    { en: "rainbow", ipa: "/ˈreɪnbəʊ/", pos: "n.", zh: "虹；彩虹" },
    { en: "square", ipa: "/skweə(r)/", pos: "n./adj.", zh: "广场；正方形的", tip: "Red Square 红场" },
    { en: "during", ipa: "/ˈdjʊərɪŋ/", pos: "prep.", zh: "在……期间" },
    { en: "victory", ipa: "/ˈvɪktəri/", pos: "n.", zh: "胜利；成功" },
    { en: "Russian", ipa: "/ˈrʌʃn/", pos: "adj./n.", zh: "俄罗斯的；俄罗斯人；俄语" },
    { en: "fight", ipa: "/faɪt/", pos: "n./v.", zh: "战斗；斗争；打仗", tip: "过去式：fought /fɔːt/" },
    { en: "against", ipa: "/əˈɡenst/", pos: "prep.", zh: "反对；与……相反；紧靠" },
    { en: "artwork", ipa: "/ˈɑːtwɜːk/", pos: "n.", zh: "艺术作品；插图" },
    { en: "tear", ipa: "/tɪə(r)/", pos: "n.", zh: "眼泪；泪水" },
    { en: "remind", ipa: "/rɪˈmaɪnd/", pos: "v.", zh: "提醒；使想起", tip: "remind sb of sth；remind sb to do sth" },
    { en: "peace", ipa: "/piːs/", pos: "n.", zh: "和平；太平", tip: "peaceful adj.；peacefully adv." },
    { en: "easily", ipa: "/ˈiːzɪli/", pos: "adv.", zh: "容易地；轻易地" },
    { en: "forget", ipa: "/fəˈɡet/", pos: "v.", zh: "忘记；遗忘", tip: "过去式：forgot" },
    { en: "noon", ipa: "/nuːn/", pos: "n.", zh: "正午；中午", tip: "at noon 在正午" },
    { en: "sick", ipa: "/sɪk/", pos: "adj.", zh: "恶心的；生病的", tip: "feel sick 感到恶心/不适" },
    { en: "metro", ipa: "/ˈmetrəʊ/", pos: "n.", zh: "地下铁道系统" },
    { en: "station", ipa: "/ˈsteɪʃn/", pos: "n.", zh: "车站；所；局", tip: "metro station 地铁站" },
    { en: "palace", ipa: "/ˈpæləs/", pos: "n.", zh: "王宫；宫殿", tip: "别和 place（地点）混淆" },
    { en: "accordion", ipa: "/əˈkɔːdiən/", pos: "n.", zh: "手风琴" },
    { en: "tower", ipa: "/ˈtaʊə(r)/", pos: "n.", zh: "塔；塔楼" },
    { en: "might", ipa: "/maɪt/", pos: "modal v.", zh: "可能；可以", tip: "may 的过去式之一" },
    { en: "budget", ipa: "/ˈbʌdʒɪt/", pos: "n./v.", zh: "预算；精打细算", tip: "go over budget 超出预算" },
    { en: "passport", ipa: "/ˈpɑːspɔːt/", pos: "n.", zh: "护照" },
    { en: "forgetful", ipa: "/fəˈɡetfl/", pos: "adj.", zh: "健忘的；好忘事的", tip: "forgetfully adv." },
    { en: "faraway", ipa: "/ˈfɑːrəweɪ/", pos: "adj.", zh: "远方的；遥远的" },
    { en: "regular", ipa: "/ˈreɡjələ(r)/", pos: "adj.", zh: "平常的；有规律的" },
    { en: "countryside", ipa: "/ˈkʌntrisaɪd/", pos: "n.", zh: "乡村；农村" },
    { en: "surprised", ipa: "/səˈpraɪzd/", pos: "adj.", zh: "惊奇的；惊讶的", tip: "be surprised to see…" },
    { en: "deer", ipa: "/dɪə(r)/", pos: "n.", zh: "鹿", tip: "复数仍是 deer" },
    { en: "probably", ipa: "/ˈprɒbəbli/", pos: "adv.", zh: "很可能；大概" },
  ],

  phrases: [
    { en: "take sb's breath away", zh: "令人惊叹；让人叹绝" },
    { en: "steamed chicken soup", zh: "汽锅鸡" },
    { en: "ready to do sth", zh: "马上要（做某事）；愿意做（某事）" },
    { en: "nothing but", zh: "只有；只是" },
    { en: "fight against sb/sth", zh: "与……作战；与……作斗争" },
    { en: "thousands of", zh: "数以千计的；成千上万的" },
    { en: "get together", zh: "聚会；相聚" },
    { en: "in the sun", zh: "在阳光下" },
    { en: "turn around", zh: "转身；翻转" },
    { en: "look for", zh: "寻找" },
    { en: "feel like doing sth", zh: "想要做某事" },
    { en: "get a good night's sleep", zh: "好好睡一觉" },
    { en: "walk through", zh: "走过；穿过" },
    { en: "travel around", zh: "四处游览" },
    { en: "a group of", zh: "一群" },
    { en: "take out", zh: "拿出" },
    { en: "on holiday / vacation", zh: "在度假" },
    { en: "go on holiday", zh: "去度假" },
  ],

  properNouns: [
    { en: "Guest-Greeting Pine", zh: "迎客松" },
    { en: "Sea of Clouds", zh: "云海" },
    { en: "Seattle", zh: "西雅图（美国城市）" },
    { en: "Red Square", zh: "红场" },
    { en: "Alexander Garden", zh: "亚历山大花园" },
    { en: "Moscow", zh: "莫斯科（俄罗斯首都）" },
    { en: "Russia", zh: "俄罗斯" },
    { en: "the Victory Museum", zh: "胜利博物馆" },
    { en: "World War II", zh: "第二次世界大战" },
    { en: "Moscow Metro", zh: "莫斯科地铁" },
    { en: "Scotland", zh: "苏格兰" },
    { en: "Mount Huangshan", zh: "黄山" },
    { en: "Yunnan", zh: "云南" },
    { en: "Lijiang", zh: "丽江" },
    { en: "Yulong Mountain", zh: "玉龙雪山" },
  ],

  adjectives: [
    { en: "great", zh: "很棒的", mood: "positive" },
    { en: "amazing", zh: "令人惊叹的", mood: "positive" },
    { en: "excellent", zh: "出色的", mood: "positive" },
    { en: "fantastic", zh: "极好的", mood: "positive" },
    { en: "relaxing", zh: "令人放松的", mood: "positive" },
    { en: "wonderful", zh: "美妙的", mood: "positive" },
    { en: "OK", zh: "还行", mood: "neutral" },
    { en: "not too bad", zh: "不算太差", mood: "neutral" },
    { en: "boring", zh: "无聊的", mood: "negative" },
    { en: "terrible", zh: "糟糕的", mood: "negative" },
  ],

  grammar: {
    title: "不定代词",
    titleEn: "Indefinite Pronouns",
    tip: "some- 多用于肯定句；any- 多用于疑问句和否定句；no- 表示否定；every- 表示全部。",
    groups: [
      { kind: "人", items: ["someone", "anyone", "no one", "everyone"] },
      { kind: "物", items: ["something", "anything", "nothing", "everything"] },
      { kind: "地点", items: ["somewhere", "anywhere", "nowhere", "everywhere"] },
    ],
    examples: [
      { q: "Did you go anywhere interesting?", a: "Yes, I went to Yunnan. / No, nowhere special." },
      { q: "Did you do anything interesting?", a: "No, nothing special. But I met someone interesting." },
      { q: "Did you eat anything special?", a: "Yes! Everything tasted good. Everyone loved it." },
    ],
    blanks: [
      {
        id: "g1",
        prompt: "Did you do ______ interesting on your holiday?",
        answer: "anything",
        options: ["anything", "something", "everything", "nothing"],
        zh: "你假期做了什么有趣的事吗？",
      },
      {
        id: "g2",
        prompt: "No, ______ special. How about you?",
        answer: "nothing",
        options: ["anything", "something", "everything", "nothing"],
        zh: "没有，没什么特别的。",
      },
      {
        id: "g3",
        prompt: "______ says the scenery around the West Lake is so beautiful.",
        answer: "Everyone",
        options: ["Someone", "Anyone", "Everyone", "No one"],
        zh: "人人都说西湖周围的风景很美。",
      },
      {
        id: "g4",
        prompt: "Did you go there with ______?",
        answer: "anyone",
        options: ["someone", "anyone", "everyone", "no one"],
        zh: "你是和谁一起去的吗？",
      },
      {
        id: "g5",
        prompt: "I got you ______ as a gift.",
        answer: "something",
        options: ["anything", "something", "everything", "nothing"],
        zh: "我给你带了点礼物。",
      },
      {
        id: "g6",
        prompt: "Like ______ else, I was ready to go on a holiday somewhere.",
        answer: "everyone",
        options: ["someone", "anyone", "everyone", "no one"],
        zh: "和其他人一样，我也准备好去度假。",
      },
      {
        id: "g7",
        prompt: "______ could join me, so I went by myself.",
        answer: "No one",
        options: ["Someone", "Anyone", "Everyone", "No one"],
        zh: "没人能和我一起，所以我自己去了。",
      },
      {
        id: "g8",
        prompt: "I could do ______ but stay in the hotel.",
        answer: "nothing",
        options: ["anything", "something", "everything", "nothing"],
        zh: "我只能待在旅馆里。",
      },
      {
        id: "g9",
        prompt: "The hotel was nice, and ______ was very clean.",
        answer: "everything",
        options: ["something", "anything", "everything", "nothing"],
        zh: "旅馆很好，一切都很干净。",
      },
      {
        id: "g10",
        prompt: "I decided to look for ______ to read.",
        answer: "something",
        options: ["anything", "something", "everything", "nothing"],
        zh: "我决定找点东西读。",
      },
      {
        id: "g11",
        prompt: "Then I heard ______ shout from outside.",
        answer: "someone",
        options: ["someone", "anyone", "everyone", "no one"],
        zh: "然后我听见外面有人喊。",
      },
      {
        id: "g12",
        prompt: "Did you go ______ interesting?",
        answer: "anywhere",
        options: ["somewhere", "anywhere", "nowhere", "everywhere"],
        zh: "你去了什么有趣的地方吗？",
      },
    ],
  },

  texts: [
    {
      id: "yaming",
      title: "Yaming 的黄山之旅",
      titleEn: "Yaming’s Trip",
      body: "Yaming went to Mount Huangshan with his family. The landscape there was amazing. Yaming saw the Guest-Greeting Pine, the Sea of Clouds, lots of strange rocks, and many ancient buildings.",
      blanks: [
        { answer: "family", hint: "家人" },
        { answer: "clouds", hint: "云" },
        { answer: "rocks", hint: "岩石" },
        { answer: "buildings", hint: "建筑" },
      ],
      cloze: "Yaming went to Mount Huangshan with his ____. The landscape there was amazing. Yaming saw the Guest-Greeting Pine, the Sea of ____, lots of strange ____, and many ancient ____.",
    },
    {
      id: "emma",
      title: "Emma 的西雅图之旅",
      titleEn: "Emma’s Trip",
      body: "Emma went back to the US with her mom and sister. She went to a strawberry festival near her grandparents' house in Seattle. At the festival, she ate some strawberry cookies and chocolates. She stayed with her grandparents for 10 days.",
      blanks: [
        { answer: "mom", hint: "妈妈" },
        { answer: "sister", hint: "姐姐/妹妹" },
        { answer: "grandparents'", hint: "祖父母的" },
        { answer: "ate", hint: "吃（过去式）" },
        { answer: "grandparents", hint: "祖父母" },
        { answer: "10", hint: "数字" },
      ],
      cloze: "Emma went back to the US with her ____ and ____. She went to a strawberry festival near her ____ house in Seattle. At the festival, she ____ some strawberry cookies and chocolates. She stayed with her ____ for ____ days.",
    },
    {
      id: "summary",
      title: "Peter 与 Adam 的假期小结",
      titleEn: "Holiday Summary",
      body: "Peter had a fantastic holiday. He went to Yunnan with his family. They stayed in the old town of Lijiang for a few days and enjoyed it very much. They visited Yulong Mountain and took a lot of photos there. They also tried some Yunnan dishes, and they ate the steamed chicken soup. Adam didn't do anything special, but he still had a relaxing and fun holiday.",
      blanks: [
        { answer: "fantastic", hint: "极好的" },
        { answer: "family", hint: "家人" },
        { answer: "town", hint: "镇" },
        { answer: "enjoyed", hint: "享受（过去式）" },
        { answer: "visited", hint: "参观（过去式）" },
        { answer: "ate", hint: "吃（过去式）" },
        { answer: "anything", hint: "任何事" },
        { answer: "fun", hint: "有趣的" },
      ],
      cloze: "Peter had a ____ holiday. He went to Yunnan with his ____. They stayed in the old ____ of Lijiang for a few days and ____ it very much. They ____ Yulong Mountain and took a lot of photos there. They also tried some Yunnan dishes, and they ____ the steamed chicken soup. Adam didn't do ____ special, but he still had a relaxing and ____ holiday.",
    },
    {
      id: "vocab-use",
      title: "假期方式短文",
      titleEn: "Ways to Spend Holidays",
      body: "People spend their holidays in different ways. Some travel to see beautiful sights and landscape in strange, faraway places. The amazing scenery makes them smile and forget their worries. Others stay comfortable at home, especially when they are tired or not feeling well. They do nothing but relax, sleep, or watch TV. Many people get together with friends and family to have a meal or play sport. There are lots of ways to relax and have fun. However, the most important part of a holiday is to rest your mind and body. Then you can go back to your regular life, and be ready to see what comes next.",
      blanks: [
        { answer: "landscape", hint: "风景" },
        { answer: "forget", hint: "忘记" },
        { answer: "especially", hint: "尤其" },
        { answer: "get together", hint: "聚会" },
        { answer: "ready", hint: "准备好" },
      ],
      cloze: "Some travel to see beautiful sights and ____ in strange, faraway places. The amazing scenery makes them smile and ____ their worries. Others stay comfortable at home, ____ when they are tired. Many people ____ with friends and family. Then you can go back to your regular life, and be ____ to see what comes next.",
    },
    {
      id: "vincent17",
      title: "Vincent 日记 · 7月17日",
      titleEn: "Vincent’s Diary — 17 July",
      body: "Today was our first day to visit Moscow. The weather was fine and everyone felt excited to visit some famous places in Russia. In the morning, we went to the Victory Museum. The Russian people built this museum to remember their fight against the Nazis during World War II. As we walked through the halls, the tour guide told us stories about the war. In one hall, I saw an artwork with thousands of glass 'tears' falling down. It reminds us that war is terrible and peace does not come easily. We should not forget that. At noon, we had lunch at a restaurant near the park. I liked the ice cream there, so I ate a lot of it. But, during dinner, I didn't feel like eating because I felt sick. So now, I just want to get a good night's sleep.",
    },
    {
      id: "vincent18",
      title: "Vincent 日记 · 7月18日",
      titleEn: "Vincent’s Diary — 18 July",
      body: "It rained last night, so this morning the air was fresh and cool. I felt much better today. We took the Moscow Metro to travel around. The metro stations are really beautiful. Sometimes I felt like I was walking inside a palace. After that, we went to Red Square. We saw some fantastic buildings there. In the afternoon, we arrived at a school and met a group of Russian students. We played games and soon became friends. Later, someone took out his accordion, and soon everyone got together to sing and dance. We were so happy that we didn't notice the time. It was such a good experience!",
    },
    {
      id: "scotland",
      title: "Gina 的苏格兰假期",
      titleEn: "My Holiday in Scotland",
      body: "Last autumn, I went on holiday to Scotland with my parents. We took a train to a small town in the countryside and stayed in a comfortable house. The scenery was beautiful and different from the big city. On the last day, early in the morning, I went into a forest to explore. While there, I turned around and saw a huge deer! I was so surprised. I ran home and told my parents what I saw. They smiled and said the deer probably lived nearby. What a wonderful experience I had!",
    },
  ],

  dialogue: {
    title: "Adam 与 Peter 的对话",
    lines: [
      { who: "Adam", text: "Hi, Peter. How are you?" },
      { who: "Peter", text: "Hi, Adam. I'm fine, thanks." },
      { who: "Adam", text: "How was your holiday?" },
      { who: "Peter", text: "It was fantastic." },
      { who: "Adam", text: "Did you go anywhere interesting?" },
      { who: "Peter", text: "Yes, I went to Yunnan with my family." },
      { who: "Adam", text: "Wow! That sounds great. Did you go to Lijiang?" },
      { who: "Peter", text: "Yes, we stayed in the old town for a few days, and we enjoyed it very much." },
      { who: "Adam", text: "Did you visit Yulong Mountain? Everyone says it's beautiful." },
      { who: "Peter", text: "It is! It just took my breath away. We took a lot of great photos there." },
      { who: "Adam", text: "Did you eat anything special?" },
      { who: "Peter", text: "Yes, we did! Everything tasted good, especially the steamed chicken soup. What about you? Someone said you went to Beijing." },
      { who: "Adam", text: "No, not this holiday. I did nothing special. I just stayed at home to read, play games, and relax, but it was still fun." },
    ],
  },

  sequences: [
    {
      id: "july17",
      title: "Vincent 7月17日行程排序",
      items: [
        { id: "a", text: "Went to the Victory Museum", zh: "去胜利博物馆" },
        { id: "b", text: "Had lunch at a restaurant near the park", zh: "在公园附近的餐厅吃午饭" },
        { id: "c", text: "Felt sick during dinner", zh: "晚饭时感觉不舒服" },
        { id: "d", text: "Wanted to get a good night's sleep", zh: "想好好睡一觉" },
      ],
      order: ["a", "b", "c", "d"],
    },
    {
      id: "july18",
      title: "Vincent 7月18日行程排序",
      items: [
        { id: "a", text: "Took the Moscow Metro to travel around", zh: "坐莫斯科地铁四处游览" },
        { id: "b", text: "Went to Red Square", zh: "去红场" },
        { id: "c", text: "Met Russian students at a school", zh: "在学校遇见俄罗斯学生" },
        { id: "d", text: "Sang and danced with accordion music", zh: "跟着手风琴唱歌跳舞" },
      ],
      order: ["a", "b", "c", "d"],
    },
    {
      id: "gina",
      title: "Gina 苏格兰经历排序",
      items: [
        { id: "a", text: "Took a train to Scotland", zh: "坐火车去苏格兰" },
        { id: "b", text: "Stayed in a comfortable countryside house", zh: "住在舒适的乡村房子里" },
        { id: "c", text: "Went into the forest", zh: "走进森林" },
        { id: "d", text: "Saw a huge deer", zh: "看见一头大鹿" },
        { id: "e", text: "Ran home and told parents", zh: "跑回家告诉父母" },
      ],
      order: ["a", "b", "c", "d", "e"],
    },
  ],

  sentenceBank: [
    {
      id: "s1",
      zh: "那风景美得让我惊叹。",
      en: "The scenery took my breath away.",
      words: ["The", "scenery", "took", "my", "breath", "away."],
    },
    {
      id: "s2",
      zh: "你假期去了什么有趣的地方吗？",
      en: "Did you go anywhere interesting on your holiday?",
      words: ["Did", "you", "go", "anywhere", "interesting", "on", "your", "holiday?"],
    },
    {
      id: "s3",
      zh: "我们如此开心，以至于没注意到时间。",
      en: "We were so happy that we didn't notice the time.",
      words: ["We", "were", "so", "happy", "that", "we", "didn't", "notice", "the", "time."],
    },
    {
      id: "s4",
      zh: "请提醒我带护照。",
      en: "Please remind me to take my passport.",
      words: ["Please", "remind", "me", "to", "take", "my", "passport."],
    },
    {
      id: "s5",
      zh: "这真是一次美妙的经历！",
      en: "What a wonderful experience I had!",
      words: ["What", "a", "wonderful", "experience", "I", "had!"],
    },
    {
      id: "s6",
      zh: "我只想好好睡一觉。",
      en: "I just want to get a good night's sleep.",
      words: ["I", "just", "want", "to", "get", "a", "good", "night's", "sleep."],
    },
  ],
};
